const fs = require('fs');
const path = require('path');
const getPackages = require('./get-packages');

const START = '<!-- START LIST_PACKAGES -->';
const END = '<!-- END LIST_PACKAGES -->';

const readme = fs.readFileSync(path.resolve(__dirname, '../README.md'), 'utf8');

const [before, rest] = readme.split(START);
const [, after] = rest.split(END);

fs.writeFileSync(
	path.resolve(__dirname, '../README.md'),
	`${before}${START}
<!-- THIS LIST IS AUTOGENERATED BY lib/update-readme.js -->

${getPackages()
	.map(
		({ pkg, path }) =>
			`-   [\`${pkg.name}\`](https://github.com/guardian/node-modules/tree/main/${path})\n` +
			`    -   ${pkg.description}.`,
	)
	.join('\n')}

${END}${after}`,
);
