import { readFileSync, writeFileSync } from 'fs';
import { createRequire } from 'module';
import path from 'path';
import { packageDirectorySync } from 'pkg-dir';

const require = createRequire(import.meta.url);
const editorconfig = readFileSync('./.editorconfig', 'utf8');
const warning = `# THIS FILE IS AUTO-GENERATED EVERY TIME YOU INSTALL ${
	require('./package.json').name
}
# DO NOT EDIT THIS FILE DIRECTLY

`;

writeFileSync(
	path.resolve(packageDirectorySync({ cwd: '../' }), '.editorconfig'),
	warning + editorconfig,
);
