import { fileURLToPath } from 'url';
import updateSection from 'update-section';
import { getPathTo } from '../../lib/get-path-to.js';

export const generateMessage = ({ label, url, updates, original }) => {
	const START = `<!-- START ${label} -->`;
	const END = `<!-- END ${label} -->`;

	function matchesStart(line) {
		return line.includes(START);
	}

	function matchesEnd(line) {
		return line.includes(END);
	}

	return updateSection(
		original,
		[
			START,
			`<!-- THIS LIST IS AUTOGENERATED BY ${getPathTo(
				fileURLToPath(url),
			)} -->`,
			'',
			...updates,
			'',
			END,
		].join('\n'),
		matchesStart,
		matchesEnd,
	);
};
