import path from 'path';
import { fileURLToPath } from 'url';
import { packageDirectorySync } from 'pkg-dir';
import updateSection from 'update-section';

export const generateMessage = ({ label, url, updates, original }) => {
	const START = `<!-- START ${label} -->`;
	const END = `<!-- END ${label} -->`;

	function matchesStart(line) {
		return line.includes(START);
	}

	function matchesEnd(line) {
		return line.includes(END);
	}

	return updateSection(
		original,
		[
			START,
			`<!-- THIS LIST IS AUTOGENERATED BY ${path.relative(
				packageDirectorySync(),
				fileURLToPath(url),
			)} -->`,
			'',
			...updates,
			'',
			END,
		].join('\n'),
		matchesStart,
		matchesEnd,
	);
};
