import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { packageDirectorySync } from 'pkg-dir';
import updateSection from 'update-section';

const START = '<!-- START PACKAGES -->';
const END = '<!-- END PACKAGES -->';

function matchesStart(line) {
	return line.includes(START);
}

function matchesEnd(line) {
	return line.includes(END);
}

export const updateReadme = (packages) => {
	const readMePath = path.resolve(packageDirectorySync(), 'README.md');

	const readme = fs.readFileSync(readMePath, 'utf8');

	const update = [
		START,
		`<!-- THIS LIST IS AUTOGENERATED BY ${path.relative(
			packageDirectorySync(),
			fileURLToPath(import.meta.url),
		)} -->`,
		'',
		...packages.map(
			({ pkg, path }) =>
				`-   [\`${pkg.name}\`](https://github.com/guardian/node-modules/tree/main/${path})\n` +
				`    -   ${pkg.description}.`,
		),
		'',
		END,
	].join('\n');

	const updated = updateSection(readme, update, matchesStart, matchesEnd);
	fs.writeFileSync(readMePath, updated);
};
