name: CI
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.0.1
      - run: make validate
